emit: [
  "@azure-tools/typespec-autorest"
]
options:
  "@azure-tools/typespec-autorest":
    "emitter-output-dir": "{project-root}/../data-plane/Microsoft.Batch/stable/2023-04-01.17.0/"
    "output-file": "BatchService.json"