emit: [
  "@azure-tools/typespec-autorest"
]
options:
  "@azure-tools/typespec-autorest":
    "emitter-output-dir": "{project-root}/../data-plane/Microsoft.Batch/preview/2022-10-01.16.0/"
    "output-file": "BatchService.json"