emit: [
  "@azure-tools/typespec-autorest"
]
options:
  "@azure-tools/typespec-autorest":
    "output-file": "BatchService.json"
  "@azure-tools/typespec-python":
    "basic-setup-py": true
    "package-version": 14.0.0b
    "package-name": azure-batch

