emitters:
  "@azure-tools/typespec-autorest": true
  # "@azure-tools/typespec-apiview": true
  "@azure-tools/typespec-python":
    "basic-setup-py": true
    "package-version": "1.0.0-beta.1"
    "package-name": "azure-confidentialledger"
  # Uncomment this line and add "@azure-tools/typespec-java" to your package.json to generate Java code
  # "@azure-tools/typespec-java": true
  # Uncomment this line and add "@azure-tools/typespec-csharp" to your package.json to generate C# code
  # "@azure-tools/typespec-csharp": true
  # Uncomment this line and add "@azure-tools/typespec-typescript" to your package.json to generate Typescript code
  # "@azure-tools/typespec-typescript": true
