parameters:  
  "service-dir":
    default: "sdk/schemaregistry"
  "dependencies":
    "additionalDirectories": []
    default: ""
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emitter-output-dir: "{project-root}"
    examples-directory: "examples"
    output-file: "SchemaRegistry.json"
  "@azure-tools/typespec-python":    
    package-dir: "azure-schemaregistry"
    package-name: "{package-dir}"  
    package-mode: dataplane
  #"@azure-tools/typespec-csharp":
  #  package-dir: "Azure.SchemaRegistry"
  #  namespace: "{package-dir}"
  #  clear-output-folder: true
  #  model-namespace: false
  #"@azure-tools/typespec-ts":
  #  package-dir: "azure-schemaregistry-rest"
  #  generateMetadata: true
  #  generateTest: true
  #  packageDetails:
  #    name: "@azure-rest/azure-schemaregistry-rest"
  #    description: "Azure.SchemaRegistry Service"
  #"@azure-tools/typespec-java":
  #  package-dir: "azure-schemaregistry"
  #  namespace: com.azure.schemaregistry
