parameters:  
  "service-dir":
    default: "sdk/sphere"
  "dependencies":
    default: ""
emit:
  - "@azure-tools/typespec-python"
options:
  "@azure-tools/typespec-python":
    package-dir: "azure-mgmt-sphere"
    package-mode: "mgmtplane"
    package-name: "{package-dir}"
