parameters:
  "service-dir":
    default: "sdk/anomalydetector"
emit: [
  "@azure-tools/typespec-autorest",
]
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    examples-directory: examples
    omit-unreachable-types: true
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
    emitter-output-dir: "{project-root}/../"
  "@azure-tools/typespec-python":
    "package-pprint-name": "\"Cognitive Services Anomaly Detector\""
    "package-mode": "dataplane"
    "package-version": 3.0.0
    "package-dir": "azure-ai-anomalydetector"
    "package-name": "{package-dir}"
  # Uncomment this line and add "@azure-tools/typespec-java" to your package.json to generate Java code
  "@azure-tools/typespec-java":
    package-dir: "azure-ai-anomalydetector"
    namespace: com.azure.ai.anomalydetector
    partial-update: true
  # Uncomment this line and add "@azure-tools/typespec-csharp" to your package.json to generate C# code
  "@azure-tools/typespec-csharp":
    save-inputs: false
    clear-output-folder: true
    package-dir: "Azure.AI.AnomalyDetector"
    namespace: "{package-dir}"
    model-namespace: false
  "@azure-tools/typespec-ts":
    package-dir: "ai-anomaly-detector-rest"
    generateMetadata: true
    generateTest: true
    packageDetails:
      name: "@azure-rest/ai-anomaly-detector"
