parameters:
  "python-sdk-folder":
    default: "{cwd}/azure-sdk-for-python/"
emit: [
  "@azure-tools/typespec-autorest",
  "@azure-tools/typespec-python",
  "@azure-tools/typespec-csharp",
]
options:
  "@azure-tools/typespec-autorest":
    "output-file": "openapi.json"
    "examples-directory": ./examples
  "@azure-tools/typespec-python":
    "package-version": 3.0.0b7
    "package-name": azure-ai-anomalydetector
    "emitter-output-dir": "{python-sdk-folder}/sdk/anomalydetector/{package-name}"
  #   "output-path":
  # Uncomment this line and add "@azure-tools/typespec-java" to your package.json to generate Java code
  "@azure-tools/typespec-java":
    namespace: com.azure.ai.anomalydetector
    partial-update: true
  # Uncomment this line and add "@azure-tools/typespec-csharp" to your package.json to generate C# code
  "@azure-tools/typespec-csharp":
    save-inputs: false
    clear-output-folder: true
    namespace: Azure.AI.AnomalyDetector
    model-namespace: false
  # Uncomment this line and add "@azure-tools/typespec-typescript" to your package.json to generate Typescript code
  # "@azure-tools/cadl-typescript": true
