parameters:
  "python-sdk-folder":
    default: "{project-root}/azure-sdk-for-python/"
  "service-directory-name":
    default: "anomalydetector"
emit: [
  "@azure-tools/typespec-autorest",
]
options:
  "@azure-tools/typespec-autorest":
    examples-directory: ./examples
    omit-unreachable-types: true
    output-file: openapi.json
    emitter-output-dir: "{project-root}/../data-plane/AnomalyDetector/stable"
  "@azure-tools/typespec-python":
    "package-pprint-name": "\"Cognitive Services Anomaly Detector\""
    "package-mode": "dataplane"
    "package-version": 3.0.0
    "package-name": "azure-ai-anomalydetector"
    "emitter-output-dir": "{python-sdk-folder}/sdk/{service-directory-name}/{package-name}"
