parameters:  
  service-dir:
    default: "sdk/openai"
emit:
#  - "@azure-tools/typespec-autorest"
#  - "@azure-tools/cadl-apiview"
options:
  # Uncomment this line and add "@azure-tools/cadl-python" to your package.json to generate Python code
  # "@azure-tools/cadl-python":
  #   "basic-setup-py": true
  #   "package-version":
  #   "package-name":
  #   "output-path":
  # Uncomment this line and add "@azure-tools/cadl-java" to your package.json to generate Java code
  # "@azure-tools/cadl-java": true
  # Uncomment this line and add "@azure-tools/cadl-csharp" to your package.json to generate C# code
  "@azure-tools/typespec-csharp":
    package-dir: "Azure.AI.OpenAI"
    namespace: "{package-dir}"
    clear-output-folder: true
    model-namespace: false
  "@azure-tools/typespec-java":
    package-dir: "azure-ai-openai"
    namespace: "com.azure.ai.openai"
    partial-update: true
    enable-sync-stack: true
    generate-tests: false
  "@azure-tools/typespec-ts":
    package-dir: "openai"
    generateMetadata: false
    generateTest: false
    isModularLibrary: true
    relative-generated-folder: "sources/generated"
    packageDetails:
      name: "@azure/openai"
